#!/usr/bin/env python3
import argparse, sys, os, subprocess, mimetypes

# This is an llvm-config inspired python script which returns some of the compile
# flags to the user. Running script like:
# $ exatn-config --includes
# prints the include directories used in the build


def main(argv=None):

    output = []

    # Print out libraries that are used in CMake
    if '--libs' in sys.argv[1:]:
        baseLibs = ['-rdynamic','-Wl,-rpath,/home/schundu3/projects/ornl_tools/build/exatn/lib',
                '-L', '/home/schundu3/projects/ornl_tools/build/exatn/lib', '-lCppMicroServices','-ltalsh', '-lexatn', '-lexatn-numerics', '-lexatn-runtime', '-lexatn-runtime-graph', '-lexatn-utils', '-ldl', '-lpthread']
        if 'YES' != 'YES':
            baseLibs += ['-lexatensor']
        exatnLibs = '/usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas.so;/usr/lib/gcc/x86_64-linux-gnu/9/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/gcc/x86_64-linux-gnu/9/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so;gfortran;/usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas.so'.split(';')
        for i,e in enumerate(exatnLibs):
            if e == 'gfortran':
                exatnLibs[i] = '-lgfortran'
            if e == 'pthread':
                exatnLibs[i] = '-lpthread'
            if e == 'dl':
                exatnLibs[i] = '-ldl'
            if e == 'm':
                exatnLibs[i] = '-lm'
            if e == 'cutensor':
                exatnLibs[i] = '-lcutensor'

        baseLibs += '/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so'.split(';') + exatnLibs
        output += baseLibs

    # Print out the linker flags used in CMake
    #if '--ldflags' in sys.argv[1:]:
        # Add the MPI and/or openMPI libraries, if they exist. Otherwise will be empty
        # Put them in strings first so they don't get added as individual letters
        #mpiFlags = '-pthread'.split(',')
        #openmpFlags = '-fopenmp'.split(',')
        #output += mpiFlags + openmpFlags

    # Print out the include directories from CMake
    if '--includes' in sys.argv[1:]:
        baseIncludes = ['/home/schundu3/projects/ornl_tools/build/exatn/include/exatn', '/home/schundu3/projects/ornl_tools/build/exatn/include', '/home/schundu3/projects/ornl_tools/build/exatn/include/cppmicroservices4']
        for b in baseIncludes:
            output += ['-I'+b]

    # Print out the CXX flags from CMake
    if '--cxxflags' in sys.argv[1:]:
        output += ['-std=gnu++14', '-fPIC'] + [' -DPATH_MAX=4096 -Wno-attributes -DNO_GPU -DEXATN_SERVICE']

    print(' '.join([c for c in output]))
    return 0

if __name__ == "__main__":
    sys.exit(main())
